### ISSUE TITLE
Add method that returns a formatted date with a string as input

### ISSUE THREAD

**Issue by pgsil** [pgsil/briefly#18]
Example:

`Briefly.format("HH:MM DD/MM/YYYY")`
returns
`21:04 10/04/1993`

**Comment by Arinzeokeke** [comment]
I dont think I understand this.
Can you Give me an example of an input and what you expect as output?

**Comment by AaronDills** [comment]
I can take a look at this

**Comment by pgsil** [comment]
@Arinzeokeke Instead of having several methods to format dates, have a single method that takes a string that dictates what the output will look like
