### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by pgsil** [pgsil/briefly#2]
Should have info on what the project is, how to install and use

**Comment by gabrielSeixas** [comment]
I'll do it!

**Comment by gabrielSeixas** [comment]
@pgsil Can I do it?

**Comment by pgsil** [comment]
@gabrielSeixas Sure!

**Comment by pgsil** [comment]
@gabrielSeixas Are you still working on this?

**Comment by gabrielSeixas** [comment]
@pgsil Yes!

**Comment by pgsil** [comment]
@gabrielSeixas Any progress? 🤔 🕰️

**Comment by diegoos** [comment]
@pgsil Can I take a look at this?

**Comment by pgsil** [comment]
@diegoos Go for it!
